#!/bin/sh
set -e
. "`dirname $0`/common.sh"

export PYTHONPATH=".:`dirname $0`/src"
python "`dirname $0`/src/lighter/main.py" -t "`dirname $0`/target" $@

# Make sure the output files are writable outside the Docker container
if [ -e "/tmp/lighter" ]; then
    chmod -R a+rwX "/tmp/lighter"
fi
