#!/bin/sh
set -e

export PYTHONPATH=".:`dirname $0`/src"
python "`dirname $0`/src/lighter/main.py" $@

# Make sure the output files are writable outside the Docker container
chmod -R a+rwX /tmp/lighter
