#!/bin/sh
set -e -x
. ./common.sh

cd "`dirname $0`"
export PYTHONPATH=".:`pwd`/src"

echo "==> Static Code Analysis for PEP8 style guide and various errors"
flake8 --statistics --count .

if [ "$TRAVIS_TAG" == "" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then
    echo "==> Executing tests with code coverage collection"
    coverage run "`dirname $0`/src/lighter/test.py" $@
else
    python "`dirname $0`/src/lighter/test.py" $@
fi
